name: 🎃 Bug
description: Bug Report
title: "[Bug]: "
labels: ["bug-report"]

body:
  - type: textarea
    id: description-area
    attributes:
      label: Description
      description: Simple and clear description of bug. Add screenshots if needed
    validations:
      required: true
  - type: textarea
  id: additional-info-area
  attributes:
    label: Additional info
    description: OS and Firefox version if needed