name: ✨ Feature
description: Feature Request
title: "[Feature Request]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: description-area
    attributes:
      label: Description
      description: Include clear explaination of the feature and how it works. Add screenshots if needed
    validations:
      required: true
  - type: textarea
  id: additional-info-area
  attributes:
    label: Additional info
    description: OS and Firefox version if needed